import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

export async function exportSeedSql(): Promise<void> {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) throw new Error("DATABASE_URL env var not set");

  const tables = [
    "tours",
    "trips",
    "bookings",
    "customers",
    "equipment",
    "training_courses",
    "training_sessions",
    "training_enrollments",
    "gallery_albums",
    "gallery_images",
  ];

  const tableFlags = tables.map((t) => `--table=${t}`).join(" ");

  console.log("📦 Exporting seed SQL...");

  const rawSql = execSync(
    `pg_dump "${dbUrl}" --data-only --no-acl --no-owner ${tableFlags}`,
    { encoding: "utf8", maxBuffer: 50 * 1024 * 1024 }
  );

  const deleteSql = `-- Idempotent delete (run before applying seed)
DO $$
DECLARE org_id text;
BEGIN
  SELECT id INTO org_id FROM organization WHERE slug = 'demo';
  IF org_id IS NOT NULL THEN
    DELETE FROM training_enrollments WHERE session_id IN (SELECT id FROM training_sessions WHERE organization_id = org_id);
    DELETE FROM training_sessions WHERE organization_id = org_id;
    DELETE FROM training_courses WHERE organization_id = org_id;
    DELETE FROM bookings WHERE organization_id = org_id;
    DELETE FROM trips WHERE organization_id = org_id;
    DELETE FROM tours WHERE organization_id = org_id;
    DELETE FROM equipment WHERE organization_id = org_id;
    DELETE FROM customers WHERE organization_id = org_id;
    DELETE FROM gallery_images WHERE album_id IN (SELECT id FROM gallery_albums WHERE organization_id = org_id);
    DELETE FROM gallery_albums WHERE organization_id = org_id;
  END IF;
END $$;`;

  const finalSql = `-- Generated by npm run seed:export on ${new Date().toISOString()}
-- DO NOT EDIT MANUALLY. Regenerate with: npm run seed:full

BEGIN;

${deleteSql}

${rawSql}

COMMIT;
`;

  const outputDir = join(process.cwd(), "scripts", "sql");
  mkdirSync(outputDir, { recursive: true });
  const outputPath = join(outputDir, "demo-seed.sql");
  writeFileSync(outputPath, finalSql, "utf8");

  const sizeKb = Math.round(finalSql.length / 1024);
  console.log(`✓ Exported ${sizeKb}KB to scripts/sql/demo-seed.sql`);
}

// Allow running directly
if (import.meta.url === `file://${process.argv[1]}`) {
  exportSeedSql().catch(console.error);
}
